version: "3.9"
services:
  user-db:
    container_name: room-db
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: room_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5437:5432"
    volumes:
      - room-db-data:/var/lib/postgresql/data
volumes:
  room-db-data: